Roomy/Roomy/Areas/BackOffice/Controllers/AuthenticationController.cs
using Roomy.Areas.BackOffice.Models;
using Roomy.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Roomy.Utils;
using Roomy.Filters;

namespace Roomy.Areas.BackOffice.Controllers
{
    
    public class AuthenticationController : Controller
    {
        private RoomyDbContext db = new RoomyDbContext();


        // GET: BackOffice/Authentication/Login
        public ActionResult Login()
        {
            return View();
        }

        // POST: BackOffice/Authentication/Login
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Login(AuthenticationLoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var passwordHash = model.Password.HashMD5();//insérer dans une variable car méthode non appelable dans linq
                var user = db.Users.SingleOrDefault(x => x.Mail == model.Login && x.Password == passwordHash);
                if (user == null)
                {
                    //1
                    //ModelState.AddModelError("", "mail ou password invalid");

                    //2
                    ViewBag.ErrorMessage = "mail ou password invalid";
                    return View(model);

                    //return RedirectToAction("Login");
                }
                else
                {
                    //ajout de la session
                    Session.Add("USER_BO", user);//nom USER_BO et la valeur de user en paramètre

                    //redirection
                    return RedirectToAction("Index", "Dashboard", new { area = "BackOffice" });
                }
                
            }
            return View(model);
        }

        // GET: BackOffice/Authentication/Login
        [AuthenticationFilter]
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home", new { area = "" });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Roomy/Roomy/Areas/BackOffice/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Roomy.Areas.BackOffice.Models;
using Roomy.Controllers;
using Roomy.Data;
using Roomy.Filters;

namespace Roomy.Areas.BackOffice.Controllers
{
    [AuthenticationFilter]
    public class CategoriesController : Controller
    {
        private RoomyDbContext db = new RoomyDbContext();

        // GET: BackOffice/Categories
        public ActionResult Index()
        {

            return View(db.Categories.ToList());
        }

        // GET: BackOffice/Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categorie categorie = db.Categories.Find(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // GET: BackOffice/Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BackOffice/Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Name")] Categorie categorie)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(categorie);
                db.SaveChanges();
                //DisplayMessage("Catégorie enregistrée", MessageType.SUCCESS);
                return RedirectToAction("Index");
            }

            return View(categorie);
        }

        // GET: BackOffice/Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categorie categorie = db.Categories.Find(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // POST: BackOffice/Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Name")] Categorie categorie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categorie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categorie);
        }

        // GET: BackOffice/Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categorie categorie = db.Categories.Find(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // POST: BackOffice/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Categorie categorie = db.Categories.Find(id);
            db.Categories.Remove(categorie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Roomy/Roomy/Areas/BackOffice/Controllers/DashboardController.cs
using Roomy.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Roomy.Areas.BackOffice.Controllers
{
    [AuthenticationFilter]
    public class DashboardController : Controller
    {
        // GET: BackOffice/Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

Roomy/Roomy/Areas/BackOffice/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Roomy.Data;
using Roomy.Filters;
using Roomy.Migrations;
using Roomy.Models;

namespace Roomy.Areas.BackOffice.Controllers
{
    [AuthenticationFilter]
    public class RoomsController : Controller
    {
        private RoomyDbContext db = new RoomyDbContext();

        // GET: BackOffice/Rooms
        public ActionResult Index()
        {
            var rooms = db.Rooms.Include(r => r.User).Include(x=>x.Category);
            return View(rooms.ToList());
        }

        // GET: BackOffice/Rooms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Room room = db.Rooms.Find(id);
            Room room = db.Rooms.Include(r => r.User).Include(x => x.Category).SingleOrDefault(x=>x.id==id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // GET: BackOffice/Rooms/Create
        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.Users, "id", "Lastname");
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name");
            return View();
        }

        // POST: BackOffice/Rooms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //Crée un jeton côté client nécessaire à l'application de la méthode POST
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Capacity,Name,Price,Description,CreatedAt,UserID,CategoryID")] Room room)//Include : paramètres inclus dans l'objet room
            //public ActionResult Create([Bind(Exclude = "Price")] Room room)//Exclude : permet d'exclure un paramètre de l'objet room
        {
            if (ModelState.IsValid)
            {
                db.Rooms.Add(room);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            
            ViewBag.UserID = new SelectList(db.Users, "id", "Lastname", room.UserID);
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", room.CategoryID);
            return View(room);
        }

        // GET: BackOffice/Rooms/Edit/5
        public ActionResult Edit(int? id)
        {
            //var old = db.Rooms.SingleOrDefault(x => x.id == Room.ID);
            //room.CreatedAt = old.CreatedAt;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Include(X => X.Files).SingleOrDefault(x => x.id==id);

            foreach (var item in room.Files)
            {
               
                  
               
            }

            //Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.Users, "ID", "Lastname", room.UserID);
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", room.CategoryID);
            return View(room);
        }

        // POST: BackOffice/Rooms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Capacity,Name,Price,Description,CreatedAt,UserID,CategoryID")] Room room)
        {
            var old = db.Rooms.Find(room.id);
            room.CreatedAt = old.CreatedAt;
            db.Entry(old).State = EntityState.Detached;


            if (ModelState.IsValid)
            {
                db.Entry(room).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.Users, "id", "Lastname", room.UserID);
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", room.CategoryID);
            return View(room);
        }

        // GET: BackOffice/Rooms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // POST: BackOffice/Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Room room = db.Rooms.Find(id);
            db.Rooms.Remove(room);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //ajout d'un fichier dans la bdd
        [HttpPost]
        public ActionResult AddFile(int id, HttpPostedFileBase upload)
        {
            var model = new RoomFile();

            model.RoomID = id;
            model.Name = upload.FileName;
            model.ContentType = upload.ContentType;

            using (var reader = new BinaryReader(upload.InputStream))
            {
                model.Content = reader.ReadBytes(upload.ContentLength);
            }

            db.RoomFiles.Add(model);
            db.SaveChanges();

            //renvoie vers l'action Edit
            return RedirectToAction("Edit", new { id = model.RoomID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Roomy/Roomy/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Roomy.Controllers
{
    public class SharedController : BaseController
    {
        // GET: Shared
        [ChildActionOnly]
        public ActionResult TopFive()
        {
            var rooms = db.Rooms.OrderByDescending(X => X.Price).Take(5);

            return View("_TopFive", rooms);
        }
    }
}

Roomy/Roomy/Areas/BackOffice/Views/Shared/_LayoutBackOffice.cshtml
@{
    Layout = null;
    var user = Session["USER_BO"] as Roomy.Models.User;

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Backoffice | @ViewBag.Title</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/roomy.css" rel="stylesheet" />

</head>
<body>
    <div class="container">
        <h1>Backoffice</h1>
        <nav class="navbar navbar-expand-lg navbar-light bg-info">
            <a class="navbar-brand" href=""></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Home", new { area="" })">App <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index", "Dashboard")">Backoffice <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Categories
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Index","Categories")">Lister</a>
                            <a class="dropdown-item" href="@Url.Action("Create","Categories")">Créer</a>

                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Salles
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Index","Rooms")">Lister</a>
                            <a class="dropdown-item" href="@Url.Action("Create","Rooms")">Créer</a>

                        </div>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li>
                </ul>
                <span class="navbar-text">
                    Bonjour @user.Firstname @user.Lastname <a href="@Url.Action("Logout","Authentication")" class="btn btn-danger">Déconnexion</a>
                </span>

            </div>
        </nav>

        @if(TempData["Message"]!=null)
        {
            <div class="alert alert-@TempData["MessageType"].ToString()">
                @TempData["Message"].ToString()
            </div>
        }



        @RenderBody()

        <footer class="bg-info">
            &copy; BACKOFFICE POEC Rouen 2018
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("SectionScripts", false)
</body>
</html>