Roomy/Roomy/Areas/BackOffice/Controllers/DashboardController.cs
using Roomy.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Roomy.Areas.BackOffice.Controllers
{
    [AuthenticationFilter]
    public class DashboardController : Controller
    {
        // GET: BackOffice/Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

Roomy/Roomy/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Roomy.Controllers
{
    public class SharedController : BaseController
    {
        // GET: Shared
        [ChildActionOnly]
        public ActionResult TopFive()
        {
            var rooms = db.Rooms.OrderByDescending(X => X.Price).Take(5);

            return View("_TopFive", rooms);
        }
    }
}

Roomy/Roomy/Controllers/UsersController.cs
using Roomy.Data;
using Roomy.Models;
using Roomy.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Roomy.Controllers
{
    public class UsersController : Controller
    {
        private RoomyDbContext db = new RoomyDbContext();
        // GET: Users





        [HttpGet]
        public ActionResult Create()
        {

            //ViewBag.NbrPersonne = 4;
            ViewBag.Civilities = db.Civilities.ToList();

            return View();
        }

        [HttpPost]
        public ActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                db.Configuration.ValidateOnSaveEnabled = false;
                //enlever le password de la base de données une fois validé
                //ModelState.Remove("Password");
                //ModelState.Remove("ConfirmedPassword");
                user.Password = user.Password.HashMD5();
                
                //enregistrer en bdd
                db.Users.Add(user);
                db.SaveChanges();
                //redirection

                TempData["Message"] = $"Utilisateur {user.Lastname} enregistré";
                return RedirectToAction("Index", "Home");

            }
            ViewBag.Civilities = db.Civilities.ToList();
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Roomy/Roomy/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/roomy.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="">Index</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="@Url.RouteUrl("AboutRoute")">About</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Create", "Users")">Nouvel Utilisateur</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <a class="navbar-brand" href="@Url.Action("Index", "Dashboard", new { area = "BackOffice" })">BackOffice</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

        </nav>
        @*Indique l'emplacement du layout*@
        @RenderBody()
        <footer class="bg-light">
            &copy; POEC Rouen 2018
            @*@Html.Partial("_TopFive")*@
            @Html.Action("TopFive", "Shared")
        </footer>


    </div>
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    @RenderSection("SectionScripts", false)

</body>
</html>

Roomy/Roomy/Views/Shared/_LayoutForm.cshtml
@{
    ViewBag.Title = "_LayoutForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>_LayoutForm</h2>

<div class="card">
    <div class="card-header">
        @RenderSection("SectionTitle", true)
    </div>
    <div class="card-body">
        @RenderBody()
    </div>
</div>

@section SectionScripts{

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("SectionScripts", false)
}

Roomy/Roomy/Views/Shared/_TopFive.cshtml
@model IEnumerable<Roomy.Models.Room>
@{
    Layout = null;
}


<div class="row">

    @foreach (var item in Model)
    {
    <div class="col-md-3">
        <p>@item.Name</p>
        <p>@item.Price  €</p>
    </div>
            }
        
    </div>